### PR TITLE
Added console_bridge

### PR DESCRIPTION
**Pull request by ahcorde**
Added:

 - console_bridge  https://github.com/ros2/docs.ros2.org/pull/33 
 - rcl_logging_spdlog https://github.com/ros2/docs.ros2.org/pull/32

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by jacobperron** [comment]
See https://github.com/ros2/docs.ros2.org/pull/33/files#r441703567 for why I'm not sure that uploading documentation for `console_bridge` is the right thing to do. As an independent project, I think it should host it's documentation independently.

**Comment by ahcorde** [comment]
I splitted this PR in two. 
 
 - This one remains for console_bridge
 - This other PR add the generated doc for rcl_logging_spdlog https://github.com/ros2/docs.ros2.org/pull/43

**Comment by ahcorde** [comment]
console_bridge_vendor is included in the build script. Can we merge this @jacobperron ?

**Review by jacobperron — APPROVED** [review]
> console_bridge_vendor is included in the build script. Can we merge this @jacobperron ?

Sure. Do you think we should regenerate the docs since the changes to the script?

**Comment by ahcorde** [comment]
The documentation has not changed since I created this PR.

**Comment by ahcorde** [comment]
I will probably update all of them in a new round.

**Pull request merged**
