### PR TITLE
Added ament_index, libstatistics_collector and rmw_dds_common

### PR DESCRIPTION
**Pull request by ahcorde**
As I mentioned in the first commit for foxy https://github.com/ros2/docs.ros2.org/pull/27#issuecomment-639298712 , there are 4 missing packages

- ament_index_cpp
- ament_index_python
- libstatistics_collector
- rmw_dds_common

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by jacobperron** [comment]
@ahcorde What steps did you take to generate the documentation for these packages?

**Comment by ahcorde** [comment]
I modified the Makefile. I will create a PR

**Review by jacobperron — APPROVED** [review]

**Comment by jacobperron** [comment]
> I modified the Makefile. I will create a PR

Please do :slightly_smiling_face:

**Comment by ahcorde** [comment]
@jacobperron, I openned the PR https://github.com/ros2/docs.ros2.org/pull/30

**Pull request merged**
