### PR TITLE
First commit of foxy

### PR DESCRIPTION
**Pull request by wjwwood**
I had to modify the `Makefile` to exclude the `api` target. I will follow up on that later.

Also, there were some warnings when generating the docs, I will follow up on those later.

I opened this just to have something in place. I did not update the links in the index to point to foxy as the readme suggests. So we will want to do that before merging or after merging this during the release announcement.

### CODE REVIEW

**Comment by ahcorde** [comment]
I was checking the diferences between my PR https://github.com/ros2/docs.ros2.org/pull/26 and yours. I also include:

- ament_index_cpp
- ament_index_python
- libstatistics_collector
- rmw_dds_common

**Comment by jacobperron** [comment]
@ahcorde I guess you modified the [Makefile](https://github.com/ros2/docs.ros2.org/blob/0ec3984a3208fa3f7c06f81ac8eeea2776c77997/Makefile) to include those extra packages?

I would say we merge this PR instead of #26 since it should contain any recent changes to documentation. (@ahcorde Sorry, I didn't know about your PR before). If we want to include docs for more packages, I think we should add them to the Makefile.

@wjwwood I think we may as well update the index.html to default to Foxy now, but I'll leave it at your discretion.

**Review by jacobperron — APPROVED** [review]

**Comment by wjwwood** [comment]
Yeah, or we could close this, and update the makefile/documentation in https://github.com/ros2/docs.ros2.org/blob/doc_gen/README.md, and then do it again.

**Comment by wjwwood** [comment]
What would you prefer @jacobperron?

**Comment by jacobperron** [comment]
> What would you prefer @jacobperron?

Either option works for me. As long as we have something for the release today.

**Comment by wjwwood** [comment]
@ahcorde sorry I also didn't see yours before, how did you include those extra repositories? I can look at doing a second round where we add docs for those too.

**Pull request merged**
