### PR TITLE
Add tracetools

### PR DESCRIPTION
**Pull request by christophebedard**
This adds `tracetools` to the list of package for API documentation.

### CODE REVIEW

**Comment by christophebedard** [comment]
I think I'm doing it right, but after the script is done running I can't find `tracetools/` under `$TMP_DIR/src/ros2/docs.ros2.org/foxy/api`. It's only under `$TMP_DIR/api/`.

What I think is weird is that in the output I see `cp -r api src/ros2/docs.ros2.org/foxy/api` at the beginning, before most of the packages have their docs built.

**Comment by christophebedard** [comment]
If https://github.com/ros2/design/pull/301 is planned to be implemented "soon" then I could just drop this.

**Review by jacobperron — APPROVED** [review]
@christophebedard Thanks for adding this. It looks like it generated correctly in #44. Is there still a issue?

I've retriggered CI since it looked like an apt flake.

**Comment by jacobperron** [comment]
> If ros2/design#301 is planned to be implemented "soon" then I could just drop this.

"soon" being the keyword :smile: I don't know the expected timeline for landing per-package documentation, but this script can hold us over in the meantime.

**Comment by christophebedard** [comment]
> It looks like it generated correctly in #44. Is there still a issue?

I should've mentioned it, but for #45 I just manually copied the `tracetools` directory and committed that :sweat_smile:

Here's the output, and I think this line here (and some lines above) should be at the end and not near the beginning: https://gist.github.com/christophebedard/6ce2ea68948c68d4bb2ab6dff55e3770#file-output_foxy-L763. Each package's documentation is generated in-repo and then copied to `$TMP_DIR/api/`. That works fine. It's just that the `cp` command to copy them to `$TMP_DIR/src/ros2/docs.ros2.org/foxy/api` is run before that. The `makefile` rules look fine so I'm not sure what I'm doing wrong.

**Comment by jacobperron** [comment]
> I should've mentioned it, but for #45 I just manually copied the tracetools directory and committed that sweat_smile

(I meant to reference #45) I see. I'll try to reproduce locally since I'd like to update all the docs for Foxy for the upcoming patch release anyways.

**Comment by jacobperron** [comment]
Yeah, there was a bug in passing the list of package names to the Makefile. I've fixed it in https://github.com/ros2/docs.ros2.org/pull/46

**Comment by christophebedard** [comment]
great, thanks @jacobperron!

**Pull request merged**
